apiVersion: v1
kind: Pod
metadata:
 name: nginxpod
 labels:
  app: nginx
spec:
 serviceAccountName: default
 containers:
  - name: nginxpod
    image: pykid/task2:v1
    ports:
     - containerPort: 80