apiVersion: v1
kind: Pod
metadata:
  creationTimestap: null
  labels:
    adhoc: pykidq7
  name: adhocpod7
spec:
 volumes:
  - name: adhocoutput
    hostPath:
     path: adhocoutput.txt
     type: File
 containers:
  - image: alpine
    name: alpine1
    volumeMounts:
     - name: adhocoutput
       mountPath: /mnt/date.txt
    command: ["/bin/sh","-c","while true; do date >> /mnt/date.txt; sleep 3;done"]
    resources: {}
 restartPolicy: Always
status: {}
