apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: adhocrspiyush14
 namespace: default
spec:
 replicas: 2
 selector:
  matchLabels:
   adhoc: piyushq4
 template:
  metadata:
   name: adhocrspiyush4
   labels:
    adhoc: piyushq4
  spec:
   containers:
    - name: adhocpiyush4
      image: pykid/exam_task1:v1
      ports:
       - containerPort: 80
      env:
       - name: x
         value: app1


