apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-24T06:46:20Z"
  labels:
    x: hello
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:x: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:x: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl.exe
    operation: Update
    time: "2020-05-24T06:46:20Z"
  name: wow2020piyush
  namespace: default
  resourceVersion: "198559"
  selfLink: /api/v1/namespaces/default/services/podexam
  uid: dfa4cf46-3c09-45d1-a813-3e9c61e5dfe5
spec:
  clusterIP: 10.111.134.124
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32703
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    x: hello
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
